### ISSUE TITLE
[FE][FEAT] 아키텍처 구조 형성

### ISSUE THREAD

**Issue by SeyeonJang** [Devocean-TechWave/OLOL-android#2]
### ⚡️ 목적
> Presentation, Domain, Data Layer 분리

<br/>

### 📋 To-do

**폴더 구조 추가**
- [x] Presentation Layer - UI, State
- [x] Domain Layer - Model, UseCase
- [x] Data Layer - API, Repository

<br/>

### 📸 스크린샷
<img width="250" alt="image" src="https://github.com/user-attachments/assets/8b1ee3fa-4a08-44d5-9003-f609571526a3">

<br/>

<br/>
